"""
Django settings for E_Commerce_Website project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import stripe
from datetime import timedelta
from environs import Env
env = Env()
env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^qpk)cka-%u_4b4m0u#=afg%wnwrjhd=efojdr*0k_a)q-yf_b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # 'jazzmin',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "crispy_forms",
    "crispy_bootstrap5",
    "fontawesome_5",
    "mathfilters",
    "drf_yasg",
    "rest_framework",
    'rest_framework_simplejwt',
    
    'core',
    'userauths',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



ROOT_URLCONF = 'E_Commerce_Website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.menu_links',
                # 'userauths.context_processors.profile_menu_links',
            ],
        },
    },
]

WSGI_APPLICATION = 'E_Commerce_Website.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"


AUTH_USER_MODEL = 'userauths.User'

# LOGIN_REDIRECT_URL = 'core:home'

# LOGIN_REDIRECT_URL = 'userauths:myadmin'

LOGOUT_REDIRECT_URL = "userauths:sign-in"

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


STRIPE_PUBLISHABLE_KEY = 'pk_test_51PQSoQBmaBkv9bws5njjZJHUKeEgHHjrp0gjkRQoAAUw4T2YC0hv0kIFLwPPA85aaGtCKwAbmFlZW2eTMUk7DyP300Tu04D1dE'
STRIPE_SECRET_KEY = 'sk_test_51PQSoQBmaBkv9bwsl2kiZB7Ur4e8S84wd5Rye6NT3RSHosAp8PflXQjA1k2jHJX0YjossoecTmyDDxJD4X7rElTp00KJufI9Ot'
STRIPE_WEBHOOK_SECRET_KEY = 'whsec_8568c361de1fc043e27a5ab1f98f7d18bd9bc4a7879ea5a4c9b336dfb76eb42c'


# ACCOUNT_LOGOUT_REDIRECT_URL = "userauths:sign-in"
# ACCOUNT_SIGNUP_REDIRECT_URL = "userauths:sign-in"

# ACCOUNT_ADAPTER = 'userauths.adapters.LoginAdapter'


# JAZZMIN_SETTINGS = {

#     # "site_header": "You order, we deliver",
#     "site_brand": "Sarthak Shop",
#     # "site_logo": "images/logo.jpg",
#     "copyright": "Sarthak-Shop.com",
#     # "order_with_respect_to": ["core", 'userauths', "transactions" , 'addon', 'blog']  
# }



# JAZZMIN_UI_TWEAKS = {
#     "navbar_small_text": False,
#     "footer_small_text": False,
#     "body_small_text": True,
#     "brand_small_text": False,
#     "brand_colour": "navbar-indigo",
#     "accent": "accent-olive",
#     "navbar": "navbar-indigo navbar-dark",
#     "no_navbar_border": False,
#     "navbar_fixed": False,
#     "layout_boxed": False,
#     "footer_fixed": False,
#     "sidebar_fixed": False,
#     "sidebar": "sidebar-dark-indigo",
#     "sidebar_nav_small_text": False,
#     "sidebar_disable_expand": False,
#     "sidebar_nav_child_indent": False,
#     "sidebar_nav_compact_style": False,
#     "sidebar_nav_legacy_style": False,
#     "sidebar_nav_flat_style": False,
#     "theme": "cyborg",
#     "dark_mode_theme": "cyborg",
#     "button_classes": {
#         "primary": "btn-primary",
#         "secondary": "btn-secondary",
#         "info": "btn-info",
#         "warning": "btn-warning",
#         "danger": "btn-danger",
#         "success": "btn-success"
#     }
# }





SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Bearer": {"type": "apiKey", "name": "Authorization", "in": "header"},
    },
    "DEFAULT_GENERATOR_CLASS": "drf_yasg.generators.OpenAPISchemaGenerator",
    "USE_SESSION_AUTH": False,  # Depending on your needs
    "VALIDATOR_URL": None,
}




REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ("userauths.api.authentication.CustomJWTAuthentication",),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "EXCEPTION_HANDLER": "E_Commerce_Website.utils.custom_exception_handler",
}



AUTHENTICATION_BACKENDS = [
    "userauths.api.backends.SQLiteBackend",
]



SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),  # Token validity
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}




EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = os.getenv("EMAIL_PORT")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
  
EMAIL_VERIFY_URL = f"http://127.0.0.1:8000/api/userauth/verify-email"



USER_BASE_URL = f"http://127.0.0.1:8000/api/userauth/"