# Generated by Django 5.0.3 on 2024-04-01 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_orderproduct_price_alter_orderproduct_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name_plural': 'Order Products'},
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancellled')], default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymnet_type', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Paypal', 'Paypal')], max_length=30)),
                ('order_id', models.IntegerField(blank=None, null=True, unique=True)),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.FloatField()),
                ('orderproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orderproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
