# Generated by Django 5.0.3 on 2024-04-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_orderproduct_options_order_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
