# Generated by Django 5.0.3 on 2024-04-03 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_payment_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
    ]
